/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Utils.DB4OUtil;
import business.customer.Customer;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.role.CustomerRole;
import business.system.EcoSystem;
import business.userAccount.UserAccount;
import java.awt.CardLayout;

import javax.swing.JPanel;

/**
 *
 * @author baochenhu
 */
public class MainJFrame extends javax.swing.JFrame {
    EcoSystem ecoSystem;
    private DB4OUtil db=new DB4OUtil();
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        ecoSystem=db.retrieveSystem();
        this.setSize(1000, 800);
        this.setLocation(200, 100);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 3, 13)); // NOI18N
        jLabel1.setText("UserName:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, 88, -1));

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 3, 13)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, -1, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, 88, -1));

        jButton1.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 256, -1, -1));

        jButton2.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 316, 81, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Authentificate the useraccount;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       UserAccount userAccount=ecoSystem.getUserAccountDirectory().AuthentificateUserAccount(jTextField1.getText(), jPasswordField1.getText());
       if(userAccount!=null){
         JPanel sysAdminJPanel=userAccount.getRole().createWorkArea(container, null, null, ecoSystem);
         CardLayout cl=(CardLayout) container.getLayout();
         container.add(sysAdminJPanel,"sysAdminJPanel");
         cl.next(container);
       }
       UserAccount enterpriseUser=null;
       
       labelOut:
       for(Network network:ecoSystem.getNetworks())
       {
          for(Enterprise enterprise:network.getEnterpriseList())
          {
             enterpriseUser=enterprise.getUserAccountDirectory().AuthentificateUserAccount(jTextField1.getText(), jPasswordField1.getText());
             if(enterpriseUser!=null)
             {
               JPanel enterpriseJPanel=enterpriseUser.getRole().createWorkArea(container, null, enterprise, ecoSystem);
               container.add(enterpriseJPanel,"enterpriseJPanel");
               CardLayout cl=(CardLayout) container.getLayout();
               cl.next(container);
               break labelOut;
             }
          }    
       }
       
       labelOut1:
       //Find the userAccount in the organization level
        for(Network network:ecoSystem.getNetworks())
       {
          for(Enterprise enterprise:network.getEnterpriseList())
          {
             for(Organization organization:enterprise.getOrganizationList()){
             UserAccount organizationUser=organization.getUserAccountDirectory().AuthentificateUserAccount(jTextField1.getText(), jPasswordField1.getText());
             if(organizationUser!=null)
             {
               JPanel organizationJPanel=organizationUser.getRole().createWorkArea(container, organization, enterprise, ecoSystem);
               container.add(organizationJPanel,"organizationJPanel");
               CardLayout cl=(CardLayout) container.getLayout();
               cl.next(container);
               break labelOut1;
             }
          }    
       }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //find the according customer
       labelOut2:
        for(Network network:ecoSystem.getNetworks())
        {
           for(Enterprise enterprise:network.getEnterpriseList())
           {
              for(Organization organization:enterprise.getOrganizationList())
              {
                if(organization instanceof CustomerOrganization)
                {
                  Customer customer=((CustomerOrganization)organization).searchForCustomer(jTextField1.getText(), jPasswordField1.getText());
                  if(customer!=null){
                     CustomerRole customerRole=customer.getRole();
                     JPanel customerJpanel=customerRole.createJPanel(customer, container, organization, enterprise, ecoSystem);
                     container.add(customerJpanel,"customerJpanel");
                     CardLayout cl=(CardLayout) container.getLayout();
                     cl.next(container);
                     break labelOut2;
                  }
                }
              }
           
           }
        }
    
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      container.removeAll();
      jTextField1.setText("");
      jPasswordField1.setText("");
      db.storeSystem(ecoSystem);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
