/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.inventoryManagerInterface;

import business.enterprise.Enterprise;
import business.organization.Organization;
import business.system.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author baochenhu
 */
public class InventoryMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryMainJPanel
     */
    JPanel container;
    Organization organization;
    Enterprise enterprise;
    EcoSystem ecosystem;
    public InventoryMainJPanel(JPanel container, Organization organization, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container=container;
        this.organization=organization;
        this.enterprise=enterprise;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Manage Category>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 98, 250, -1));

        jButton2.setText("Manage Product>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 216, 250, -1));

        jButton3.setText("Process WorkQueue>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 326, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManageProductJPanel manageProductJPanel=new ManageProductJPanel(container, organization, enterprise, ecosystem);
        container.add(manageProductJPanel,"manageProductJPanel");
        CardLayout cl=(CardLayout) container.getLayout();
        cl.next(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManageCategoryJPanel manageCategoryJPanel=new ManageCategoryJPanel(container, organization, enterprise, ecosystem);
        container.add(manageCategoryJPanel,"manageCategoryJPanel");
        CardLayout cl=(CardLayout) container.getLayout();
        cl.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ProcessWorkQueueJPanel processWorkQueueJPanel=new ProcessWorkQueueJPanel(container, organization, enterprise, ecosystem);
        container.add(processWorkQueueJPanel,"manageCategoryJPanel");
        CardLayout cl=(CardLayout) container.getLayout();
        cl.next(container);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
