/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.inventoryManagerInterface;

import business.product.Product;
import business.enterprise.Enterprise;
import business.organization.InventoryOrganization;
import business.organization.Organization;
import business.product.Category;
import business.system.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baochenhu
 */
public class ManageProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryMainJPanel
     */
    JPanel container;
    Organization organization;
    Enterprise enterprise;
    EcoSystem ecosystem;
    public ManageProductJPanel(JPanel container, Organization organization, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container=container;
        this.organization=organization;
        this.enterprise=enterprise;
        this.ecosystem=ecosystem;
        populateTable();
        populateCategoryComboBox();
    }
    public void populateTable()
    {  DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
       for(Category category:((InventoryOrganization)organization).getCategoryCatalog())
       {
          for(Product product:category.getProductList())
          {
          Object[] obj=new Object[4];
          obj[0]=category;
          obj[1]=product;
          obj[2]=product.getPrice();
          obj[3]=product.getAvailability();    
          model.addRow(obj);
          }
       } 
    }
   public void populateCategoryComboBox(){
      InventoryOrganization inventoryOrganization=(InventoryOrganization) organization;
      jComboBox1.removeAllItems();
      for(Category category:inventoryOrganization.getCategoryCatalog())
      {
         jComboBox1.addItem(category);
      } 
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "ProductName", "ProductPrice", "ProductQuantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, 521, 164));

        jLabel1.setText("Product Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 287, -1));

        jLabel2.setText("Product Price:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel3.setText("Product Quantity:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 287, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 287, -1));

        jButton1.setText("Add>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        jLabel4.setText("Product Decription:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 287, -1));

        jButton2.setText("Delete>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jButton3.setText("Update>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jButton4.setText("<<Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel5.setText("Category:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 280, -1));

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        InventoryOrganization inventoryOrganization=(InventoryOrganization) organization;
        Category category=(Category) jComboBox1.getSelectedItem();
//        Product product=category.createAndAddProduct();
//        product.setProductName(jTextField1.getText());
        
        float productPrice=Float.parseFloat(jTextField2.getText());
        int productAvailability=Integer.parseInt(jTextField3.getText());
        if(productPrice>0 && productAvailability>0){
        Product product=category.createAndAddProduct();
        product.setProductName(jTextField1.getText());
        product.setPrice(productPrice);
        product.setAvailability(productAvailability);
        
        product.setProductDescription(jTextField4.getText());
        product.setSupplyEnterprise(enterprise);
        product.setCategory(category);
        populateTable();
        }else{
          JOptionPane.showMessageDialog(null, "The Number should be large than 0");
        }
       }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "You have enter the wrong number");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int selectedRow=jTable1.getSelectedRow();
       if(selectedRow>=0)
       {
          Product product=(Product) jTable1.getValueAt(selectedRow, 1);
          for(Category category : ((InventoryOrganization)organization).getCategoryCatalog())
          {
             category.removeProductFromList(product);
          }
       }
       populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        container.remove(this);
       CardLayout cl=(CardLayout) container.getLayout();
       cl.previous(container);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int selectedItem=jTable1.getSelectedRow();
       if(selectedItem>=0)
       {
          Product product=(Product) jTable1.getValueAt(selectedItem, 1);
          UpdateProductJPanel updateProductJPanel=new UpdateProductJPanel(container, product);
          container.add(updateProductJPanel,"updateProductJPanel");
          CardLayout cl=(CardLayout) container.getLayout();
          cl.next(container);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       populateTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
