/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.inventoryManagerInterface;

import business.enterprise.Enterprise;
import business.organization.InventoryOrganization;
import business.organization.Organization;
import business.product.Category;
import business.system.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baochenhu
 */
public class ManageCategoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCategoryJPanel
     */
    JPanel container;
    Organization organization;
    Enterprise enterprise;
    EcoSystem ecosystem;
    public ManageCategoryJPanel(JPanel container, Organization organization, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container=container;
        this.organization=organization;
        this.enterprise=enterprise;
        this.ecosystem=ecosystem;
        populateTable();
    }
    public void populateTable(){
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
       for(Category category:((InventoryOrganization)organization).getCategoryCatalog())
       {
          Object obj[]=new Object[1];
          obj[0]=category;
          model.addRow(obj);
       }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "CategoryName"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 534, 198));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 360, -1, -1));

        jLabel1.setText("CategoryName:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 283, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 277, 299, -1));

        jButton2.setText("Add>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 360, -1, -1));

        jButton3.setText("Delete>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       InventoryOrganization inventoryOrganization=(InventoryOrganization)organization;
       Category category=inventoryOrganization.createAndAddCategory();
       category.setCategoryName(jTextField1.getText());
       populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       container.remove(this);
       CardLayout cl=(CardLayout) container.getLayout();
       cl.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedItem=jTable1.getSelectedRow();
        if(selectedItem>=0)
        {
           Category category=(Category) jTable1.getValueAt(selectedItem, 0);
           InventoryOrganization inventoryOrganization=(InventoryOrganization)organization;
           inventoryOrganization.deleteCategoryFromCatalog(category);
           populateTable();
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
