/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.enterpriseAdminRole;

import business.enterprise.AmazonEnterprise;
import business.enterprise.Enterprise;
import business.enterprise.SupplierEnterprise;
import business.organization.Organization;
import business.system.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author baochenhu
 */
public class EnterpriseAdminJPanel extends javax.swing.JPanel {
   JPanel container;
   Enterprise enterprise;
   EcoSystem ecosystem;
    /**
     * Creates new form EnterpriseAdminJPanel
     */
    public EnterpriseAdminJPanel(JPanel container, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container=container;
        this.enterprise=enterprise;
        this.ecosystem=ecosystem;
        populateTree();
        jLabel2.setVisible(false);
        jLabel1.setText(enterprise.getEnterpriseName());
        decideVisibiliy();
    }
    /*
     * populate the tree the chehc the structure of the whole enterprise
     */
    public void populateTree(){
       int counter=0;
       DefaultTreeModel model=(DefaultTreeModel) jTree1.getModel();
       DefaultMutableTreeNode root=(DefaultMutableTreeNode) model.getRoot();
       for(Organization org:enterprise.getOrganizationList())
       {
          DefaultMutableTreeNode orgNode=new DefaultMutableTreeNode(org);
          root.insert(orgNode, counter);
          counter++;
       }
       model.reload();
    }
    
    public void decideVisibiliy(){
       if(enterprise instanceof AmazonEnterprise)
       {
          jButton4.setVisible(false);
          jButton5.setVisible(false);
          jButton6.setVisible(false);
       }else{
       
          jButton4.setVisible(true);
          jButton5.setVisible(true);
          jButton6.setVisible(true);
           if(((SupplierEnterprise)enterprise).getLocation()==null)
             jLabel2.setVisible(true);
           else{
             jLabel2.setVisible(false);
           }
       }
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Enterprise");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 94, 186, 361));

        jButton1.setText("Manage Organization>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 116, 290, -1));

        jButton2.setText("Manage Employee>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 290, -1));

        jButton3.setText("Manage UserAccount>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 290, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 18)); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 23, 273, 31));

        jButton4.setText("Manage Location>>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 290, -1));

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 3, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Please Enter Your Location First ! !");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 250, 39));

        jButton5.setText("View Ratings And Reviews>>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 290, -1));

        jButton6.setText("Analysis>>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ManageOrganizationJPanel manageOrganizationJPanel=new ManageOrganizationJPanel(container,enterprise,ecosystem);
       container.add(manageOrganizationJPanel,"manageEmployeeJPanel");
       CardLayout cl=(CardLayout) container.getLayout();
       cl.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ManageEmployeeJPanel manageEmployeeJPanel=new ManageEmployeeJPanel(container,enterprise,ecosystem);
       container.add(manageEmployeeJPanel,"manageEmployeeJPanel");
       CardLayout cl=(CardLayout) container.getLayout();
       cl.next(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       ManageUserAccountJPanel manageUserAccountJPanel=new ManageUserAccountJPanel(container,enterprise,ecosystem);
       container.add(manageUserAccountJPanel,"manageUserAccountJPanel");
       CardLayout cl=(CardLayout) container.getLayout();
       cl.next(container);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       ManageEnterpriseLocationJPanel manageEnterpriseLocationJPanel=new ManageEnterpriseLocationJPanel(container,enterprise);
       container.add(manageEnterpriseLocationJPanel,"manageEnterpriseLocationJPanel");
       CardLayout cl=(CardLayout) container.getLayout();
       cl.next(container);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       ViewRatingAndReviewJPanel viewRatingAndReviewJPanel=new ViewRatingAndReviewJPanel(container,enterprise,ecosystem);
       container.add(viewRatingAndReviewJPanel,"viewRatingAndReviewJPanel");
       CardLayout cl=(CardLayout) container.getLayout();
       cl.next(container);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       AnalysisJPanel analysisJPanel=new AnalysisJPanel(container,enterprise,ecosystem);
       container.add(analysisJPanel,"analysisJPanel");
       CardLayout cl=(CardLayout) container.getLayout();
       cl.next(container);
    }//GEN-LAST:event_jButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
