/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.enterpriseAdminRole;

import business.employee.Employee;
import business.enterprise.AmazonEnterprise;
import business.enterprise.Enterprise;
import business.enterprise.SupplierEnterprise;
import business.organization.Organization;
import business.role.Role;
import business.system.EcoSystem;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baochenhu
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {
    JPanel container;
    Enterprise enterprise;
    EcoSystem ecosystem;
    /**
     * Creates new form ManageUserAccountJPanel
     */
    public ManageUserAccountJPanel(JPanel container, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container=container;
        this.enterprise=enterprise;
        this.ecosystem=ecosystem;
        populateOrganization();
        populateRole();
        populateTable();
    }
    private void populateTable(){
      DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
      model.setRowCount(0);
      for(Organization org:enterprise.getOrganizationList())
      {
         for(UserAccount ua:org.getUserAccountDirectory().getUserAccountList())
         {
            Object[] obj=new Object[2];
            obj[0]=ua;
            obj[1]=ua.getRole();
            model.addRow(obj);
         }
      
      }
    }
    public void populateOrganization(){
       jComboBox1.removeAllItems();
       for(Organization organization:enterprise.getOrganizationList())
       {
          jComboBox1.addItem(organization);
       }
    }
    
    public void populateEmployee(){
       jComboBox2.removeAllItems();
       Organization organization=(Organization) jComboBox1.getSelectedItem();
       if(organization!=null)
       {
         for(Employee employee:organization.getEmployeeDirectory().getEmployeeList())
         {
            jComboBox2.addItem(employee);
         }      
       }  
    }
    public void populateRole(){
       jComboBox3.removeAllItems();
       if(enterprise instanceof AmazonEnterprise)
       for(Role role:((AmazonEnterprise)enterprise).getSupportedRole())
              jComboBox3.addItem(role);
       if(enterprise instanceof SupplierEnterprise)
         for(Role role:((SupplierEnterprise)enterprise).getSupportedRole())
              jComboBox3.addItem(role);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Role"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 17, 520, 130));

        jLabel1.setText("Organization:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 200, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 196, 227, -1));

        jLabel2.setText("Employee:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 257, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 253, 227, -1));

        jLabel3.setText("Role:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 323, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 319, 227, -1));

        jLabel4.setText("UserName:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 377, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 371, 227, -1));

        jLabel5.setText("Passwork:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 429, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 423, 227, -1));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 480, -1, -1));

        jButton2.setText("create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 480, -1, -1));

        jButton3.setText("Delete>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        populateEmployee();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       container.remove(this);
       CardLayout cl=(CardLayout) container.getLayout();
       cl.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Organization org =(Organization)jComboBox1.getSelectedItem();
       Employee emp=(Employee) jComboBox2.getSelectedItem();
       Role role=(Role) jComboBox3.getSelectedItem();
       UserAccount ua=org.getUserAccountDirectory().createAndAddUserAccount();
       ua.setEmployee(emp);
       ua.setRole(role);
       ua.setUserName(jTextField1.getText());
       ua.setPasswork(jTextField2.getText());
       ua.setWorkQueue(null);
       populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedItem= jTable1.getSelectedRow();
        UserAccount ua=(UserAccount) jTable1.getValueAt(selectedItem, 0);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
