/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.enterpriseAdminRole;

import business.enterprise.Enterprise;
import business.enterprise.RateAndReview;
import business.enterprise.SupplierEnterprise;
import business.network.Network;
import business.system.EcoSystem;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baochenhu
 */
public class ViewRatingAndReviewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewRatingAndReviewJPanel
     */
    JPanel container;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    public ViewRatingAndReviewJPanel(JPanel container,Enterprise enterprise,EcoSystem ecoSystem) {
        initComponents();
        this.container=container;
        this.enterprise=enterprise;
        this.ecoSystem=ecoSystem;
        populateTable();
        setRating();
        getRank();
    }
    
    
    public void populateTable(){
       DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
       for(RateAndReview rar:((SupplierEnterprise)enterprise).getRateAndReviewDir())
       {
          Object[] obj=new Object[1];
          obj[0]=rar.getReviews();
          model.addRow(obj);
       
       }
    
    }
    public void getRank(){
       Map<String,String> sortedMap=ecoSystem.rank();
       DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
       model.setRowCount(0);
       int i=1;
       for(Map.Entry entry:sortedMap.entrySet())
       {
         Object[] obj=new Object[3];
         obj[0]=i;
         obj[2]=entry.getKey();
         obj[1]=entry.getValue();
         model.addRow(obj);
         i++;
       }
    
    }
    
//    public int getRating(){
//        int total=0;
//        int i=1;
//        int rate=0;
//        if(((SupplierEnterprise)enterprise).getRateAndReviewDir().size()>0){
//            for(RateAndReview rar:((SupplierEnterprise)enterprise).getRateAndReviewDir()){
//              total+=rar.getRateNum();
//              i++;
//            }
//            rate=total/i;
//        }
//       return rate;
//    
//    }
    public void setRating(){
       switch(((SupplierEnterprise)enterprise).getRating()){
           case 1:
               jRadioButton1.setSelected(true);
               break;
           case 2:
               jRadioButton1.setSelected(true);
               jRadioButton2.setSelected(true);
               break;
           case 3:
               jRadioButton1.setSelected(true);
               jRadioButton2.setSelected(true);
               jRadioButton3.setSelected(true);
               break;
           case 4:
               jRadioButton1.setSelected(true);
               jRadioButton2.setSelected(true);
               jRadioButton3.setSelected(true);
               jRadioButton4.setSelected(true);
               break;
           case 5:
               jRadioButton1.setSelected(true);
               jRadioButton2.setSelected(true);
               jRadioButton3.setSelected(true);
               jRadioButton4.setSelected(true);
               jRadioButton5.setSelected(true);
               break;
       }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Your Enterprise Average Rating is:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 32, 224, -1));

        jRadioButton1.setEnabled(false);
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 82, -1, -1));

        jRadioButton2.setEnabled(false);
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 82, -1, -1));

        jRadioButton3.setEnabled(false);
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 82, -1, -1));

        jRadioButton4.setEnabled(false);
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 82, -1, -1));

        jRadioButton5.setEnabled(false);
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 82, -1, -1));

        jLabel2.setText("Your Rank In the entire system is:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Review"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 362, 479, 133));

        jLabel3.setText("All The Reviews:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 340, -1, -1));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 534, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ranking", "EnterpriseName", "Score"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 164, 483, 148));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       container.remove(this);
       CardLayout cl=(CardLayout) container.getLayout();
       cl.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
