/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.customer;

import business.customer.Customer;
import business.customer.OrderItem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.product.Category;
import business.product.Product;
import business.system.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baochenhu
 */
public class CustomerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkArea
     */
    
    JPanel container;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    Customer customer;
    Organization organization;
    public CustomerWorkArea(Customer customer,JPanel container,Organization organization,Enterprise enterprise,EcoSystem ecoSystem) {
        initComponents();
        this.customer=customer;
        this.container=container;
        this.enterprise=enterprise;
        this.organization=organization;
        this.ecoSystem=ecoSystem;
        jLabel2.setText(customer.getCustomerName());
  //      populateRecommendedSystemTable();
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    
    public void populateRecommendedSystemTable(){
       DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
       for(OrderItem orderItem:customer.getViewingHistory().getViewedOrderItems())
       {
          Category category=orderItem.getProduct().getCategory();
          for(Product product:category.getProductList())
          {
             Object[] obj=new Object[3];
             obj[0] = product;
             obj[1] = product.getCategory();
             obj[2] = product.getSupplyEnterprise();
             model.addRow(obj);
          }
       }
      

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jButton1.setText("View and Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 170, 243, -1));

        jButton2.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jButton2.setText("View Order Status And History");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 252, 243, -1));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Welcome:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 29, 170, -1));

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 74, -1));

        jButton4.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jButton4.setText("Manage Location");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 243, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ProductName", "Category", "Supplier"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 580, 160));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel3.setText("Product You May Want:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, -1));

        jButton3.setText("View>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViewProductsJPanel viewProductsJPanel=new ViewProductsJPanel(customer, container, organization, enterprise, ecoSystem);
        container.add(viewProductsJPanel, "viewProductsJPanel");
        CardLayout cl=(CardLayout) container.getLayout();
        cl.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       ManageLocationJPanel manageLocationJPanel=new ManageLocationJPanel(customer,container);
       container.add(manageLocationJPanel, "manageLocationJPanel");
       CardLayout cl=(CardLayout) container.getLayout();
       cl.next(container);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ViewAndOrderJPanel viewAndOrderJPanel=new ViewAndOrderJPanel(customer, container, organization, enterprise, ecoSystem);
        container.add(viewAndOrderJPanel, "viewAndOrderJPanel");
        CardLayout cl=(CardLayout) container.getLayout();
        cl.next(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       populateRecommendedSystemTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
