/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.customer;

import business.customer.Order;
import business.customer.OrderItem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baochenhu
 */
public class EditCartJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditCartJPanel
     */
    JPanel container;
    Order order;
    public EditCartJPanel(JPanel container,Order order) {
        initComponents();
        this.container=container;
        this.order=order;
        populateOrderItems();
        setSubTotalLable();
    }
    
    private void populateOrderItems(){
       DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
       for(OrderItem orderItem:order.getOrderItems()){
           Object[] obj=new Object[3];
           obj[0] = orderItem;
           obj[1] = orderItem.getProduct().getPrice();
           obj[2] = orderItem.getQuantity();
           model.addRow(obj);
       }
    
    }
    
    private void deleteOrderItem(){
        int selectedItem1 = jTable1.getSelectedRow();
        if(selectedItem1 >= 0){
          OrderItem orderItem=(OrderItem) jTable1.getValueAt(selectedItem1, 0);        
          order.deleteOrderItem(orderItem);
          populateOrderItems();
        }
    }
    
    private void setSubTotalLable(){
       jLabel3.setText(order.calSubTotal()+"");
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 24, 489, 162));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 322, -1, -1));

        jLabel1.setText("Quantity:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 240, 91, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 234, 71, -1));

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 235, 203, -1));

        jLabel2.setText("SubTotal:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 198, 68, -1));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 198, 78, -1));

        jLabel4.setText("$");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 198, 19, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 290, 203, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedItem = jTable1.getSelectedRow();
        if(selectedItem>=0 && !jTextField1.getText().equals("")){
           OrderItem orderItem = (OrderItem) jTable1.getValueAt(selectedItem, 0);
           orderItem.setQuantity(Integer.parseInt(jTextField1.getText()));
        }
        populateOrderItems();
        setSubTotalLable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      container.remove(this);
      CardLayout cl=(CardLayout) container.getLayout();
      cl.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       deleteOrderItem();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
