/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.sysAdminWorkArea;

import business.network.Network;
import business.system.EcoSystem;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.ListModel;

/**
 *
 * @author baochenhu
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {
    JPanel container;
    EcoSystem ecoSystem;
    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel container,EcoSystem ecoSystem) {
        initComponents();
        this.container=container;
        this.ecoSystem=ecoSystem;
        populateJList();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Network Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 71, 146, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 65, 235, -1));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 151, -1, -1));

        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 151, -1, -1));

        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 244, 254, -1));

        jLabel2.setText("Existing Network:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 259, -1, -1));

        jButton3.setText("Update");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 423, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
   private void populateJList(){
      DefaultListModel model=new DefaultListModel();
      
      for(Network network:ecoSystem.getNetworks()){
        model.addElement(network);
      
      }
      jList1.setModel(model);
     
   }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Network network=ecoSystem.createAndAddNetwork();
        network.setName(jTextField1.getText());       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       container.remove(this);
       CardLayout cl=(CardLayout) container.getLayout();
       cl.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
