/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.sysAdminWorkArea;

import business.employee.Employee;
import business.enterprise.Enterprise;
import business.network.Network;
import business.role.EnterpriseAdminRole;
import business.system.EcoSystem;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baochenhu
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {
    JPanel container;
    EcoSystem ecoSystem;
    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel container,EcoSystem ecoSystem) {
        initComponents();
        this.container=container;
        this.ecoSystem=ecoSystem;
        populateNetwork();
        populateTable();
    }

    
    public void populateNetwork(){
      jComboBox1.removeAllItems();
      for(Network network:ecoSystem.getNetworks())
      {
         jComboBox1.addItem(network);
      
      }
    
    }
    public void populateEnterprise(){
       jComboBox2.removeAllItems();
       Network network=(Network) jComboBox1.getSelectedItem();
       for(Enterprise enterprise: network.getEnterpriseList())
       {
          jComboBox2.addItem(enterprise);
       
       }
    }
    public void populateTable(){
       DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
       for(Network network:ecoSystem.getNetworks())
       {
          for(Enterprise enterprise:network.getEnterpriseList())
          {
             Object[] obj=new Object[2];
             
             for(UserAccount ua:enterprise.getUserAccountDirectory().getUserAccountList())
             {
                if(ua.getRole() instanceof EnterpriseAdminRole)
                {
                  obj[0]=enterprise.getEnterpriseName();
                  obj[1]=ua;
                }
             }
             model.addRow(obj);
          }
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Network:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 244, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 240, 233, -1));

        jLabel2.setText("Enterprise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 311, -1, -1));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 307, 233, -1));

        jLabel3.setText("Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 352, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 352, 233, -1));

        jLabel4.setText("UserName:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 404, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 398, 233, -1));

        jLabel5.setText("Password:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 458, -1, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 452, 233, -1));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 498, -1, -1));

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 498, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise", "Admin"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 20, 553, 177));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       populateEnterprise();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Enterprise enterprise=(Enterprise) jComboBox2.getSelectedItem();
        Employee employee=enterprise.getEmployeeDirectory().createAndAddEmployee();
        employee.setName(jTextField1.getText());
        
        UserAccount userAccount=enterprise.getUserAccountDirectory().createAndAddUserAccount();
        userAccount.setEmployee(employee);
        userAccount.setUserName(jTextField2.getText());
        userAccount.setPasswork(jTextField3.getText());
        userAccount.setRole(new EnterpriseAdminRole());
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         container.remove(this);
       CardLayout cl=(CardLayout) container.getLayout();
       cl.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
