/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.sysAdminWorkArea;

import business.enterprise.Enterprise;
import business.enterprise.Enterprise.EnterpriseType;
import business.network.Network;
import business.system.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author baochenhu
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {
    JPanel container;
    EcoSystem ecoSystem;
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel container,EcoSystem ecoSystem) {
        initComponents();
        this.container=container;
        this.ecoSystem=ecoSystem;
        populateEnterpriseType();
        populateNetworkComboBox();
    }
    
    public void populateNetworkComboBox(){
      jComboBox1.removeAllItems();
      for(Network network:ecoSystem.getNetworks())
      {
         jComboBox1.addItem(network);
      } 
    }
    private void populateEnterpriseType(){
       jComboBox2.removeAllItems();
       for(EnterpriseType enterpriseType:Enterprise.EnterpriseType.values()){
          jComboBox2.addItem(enterpriseType);    
       }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Network:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 71, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 67, 207, -1));

        jLabel2.setText("Enterprise Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 148, -1, -1));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 144, 209, -1));

        jLabel3.setText("Enterprise Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 231, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 225, 203, -1));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 328, -1, -1));

        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 328, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Network network=(Network) jComboBox1.getSelectedItem();
       String enterpriseName=((Enterprise.EnterpriseType)jComboBox2.getSelectedItem()).getValue();
       Enterprise enterprise=network.createAndAddEnterprise(enterpriseName);
       enterprise.setEnterpriseName(jTextField1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        container.remove(this);
       CardLayout cl=(CardLayout) container.getLayout();
       cl.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
