/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.sysAdminWorkArea;

import business.enterprise.Enterprise;
import business.network.Network;
import business.system.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author baochenhu
 */
public class SysAdminWorkArea extends javax.swing.JPanel {
    JPanel container;
    EcoSystem ecoSystem;
    /**
     * Creates new form SysAdminWorkArea
     */
    public SysAdminWorkArea(JPanel container,EcoSystem ecoSystem) {
        this.container=container;
        this.ecoSystem=ecoSystem;
        initComponents();
        populateJTree();
    }
   
    public void populateJTree(){
       DefaultTreeModel model=(DefaultTreeModel) jTree1.getModel();
       DefaultMutableTreeNode networkNode;
       DefaultMutableTreeNode enterpriseNode;
       DefaultMutableTreeNode root=(DefaultMutableTreeNode) model.getRoot();
       
       root.removeAllChildren();
       int count=0;
       for(Network network:ecoSystem.getNetworks())
       {
          networkNode=new DefaultMutableTreeNode(network);
          root.insert(networkNode, count);
          count++;
          for(int i=0;i<network.getEnterpriseList().size();i++){
             enterpriseNode=new DefaultMutableTreeNode(network.getEnterpriseList().get(i));
             networkNode.insert(enterpriseNode, i);
          }
       }
       model.reload();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Manage Network");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 128, 159, -1));

        jLabel1.setText("System Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 22, -1, -1));

        jButton2.setText("Manage Enterprise");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 208, -1, -1));

        jButton3.setText("Manage Enterprise Admin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 302, 186, -1));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 95, 216, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(container,ecoSystem);
        container.add(manageNetworkJPanel,"manageNetworkJPanel");
        CardLayout cl=(CardLayout) container.getLayout();
        cl.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManageEnterpriseJPanel manageEnterpriseJPanel=new ManageEnterpriseJPanel(container,ecoSystem);
        container.add(manageEnterpriseJPanel,"manageEnterpriseJPanel");
        CardLayout cl=(CardLayout) container.getLayout();
        cl.next(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminJPanel(container,ecoSystem);
        container.add(manageEnterpriseAdminJPanel,"manageEnterpriseAdminJPanel");
        CardLayout cl=(CardLayout) container.getLayout();
        cl.next(container);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
